# Generated by Django 4.2.3 on 2023-07-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recent_projects',
            new_name='place',
        ),
    ]
