# Generated by Django 4.2.3 on 2023-07-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_rename_recent_projects_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profile_picture', models.ImageField(upload_to='Avatar')),
                ('description', models.TextField()),
            ],
        ),
    ]
